language: generic
env:
  global:
      # set this to the repo which should have the resulting PDF's
      - GITHUB_REPO="hpcugent/vsc_user_docs"
      # this is an encrypted version of an access token for the repo above.
      # Create it by using the travis tool: travis encrypt -r $GITHUB_REPO GH_TOKEN=<TOKEN>
      # and replace it below
      - secure: 2p42CdapsQR6xkcR/cnqngbwwYqol7QKosxa6n7r4HhKFw7pcaSRWa/5fLOKIunMxW56UfQgTHCecGAU5/oWS8jmEVZYpBThynQBsHBt4xtPw4RUJzAwn6BmWeKX4RHKE6CCcscxAa1Q9vxBWJ0/yRLSP/ikfj6cAH33ga00dFA=
      - CACHEDIR=$HOME/cached
before_install:
    # verify SHA256 checksums to ensure version is bumped when changes are made
    # if this check fails, you should run ./check-version.sh intro-HPC and commit the changes made by the script
    - INTRO_HPC_EXPECTED="20180904.05 3d8923f6c8b94d1ed617d13db306ce9d4538f75cde93eb5ed9d94b4505d62e4f"
    - INTRO_LINUX_EXPECTED="20180904.02 b7538bc4ff3c4856f75acdea9d3176a813995f540caa2fd67eac316ea771667f"
    - ./check-version.sh intro-HPC > check_version_intro_hpc.out 2>&1
    - cat check_version_intro_hpc.out
    - grep "Checksum for intro-HPC is still valid" check_version_intro_hpc.out
    - ./check-version.sh intro-Linux > check_version_intro_linux.out 2>&1
    - cat check_version_intro_linux.out
    - grep "Checksum for intro-Linux is still valid" check_version_intro_linux.out
install:
    - ./travis-install.sh
    - export PATH=$CACHEDIR/.texlive/bin/x86_64-linux:$PATH
    - pdflatex --version ; latexmk --version
script:
    - cd $TRAVIS_BUILD_DIR
    - make all
after_success:
    - mkdir -p $HOME/build
    - cp -a */*.pdf $HOME/build
    - ls $HOME/build
deploy:
  skip_cleanup: true
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  on:
      repo: $GITHUB_REPO
      branch: master

cache:
    directories:
        - $CACHEDIR
