language: generic
env:
  global:
      # set this to the repo which should have the resulting PDF's
      - GITHUB_REPO="hpcugent/vsc_user_docs"
      # this is an encrypted version of an access token for the repo above.
      # Create it by using the travis tool: travis encrypt -r $GITHUB_REPO GH_TOKEN=<TOKEN>
      # and replace it below
      - secure: 2p42CdapsQR6xkcR/cnqngbwwYqol7QKosxa6n7r4HhKFw7pcaSRWa/5fLOKIunMxW56UfQgTHCecGAU5/oWS8jmEVZYpBThynQBsHBt4xtPw4RUJzAwn6BmWeKX4RHKE6CCcscxAa1Q9vxBWJ0/yRLSP/ikfj6cAH33ga00dFA=
      - CACHEDIR=$HOME/cached
before_install:
    # verify SHA256 checksums to ensure version is bumped when changes are made
    # if this check fails, you should run ./check-version.sh intro-HPC and commit the changes made by the script
    - INTRO_HPC_EXPECTED="20180831.03 85d188f3ee70b335f487d0a11ba1b69d155d04f18bf82145716f77cb49785e6f"
    - INTRO_LINUX_EXPECTED="20180831.01 fdca1acbd7f9a279fbc08337807933e89a4ff46445d438011ac794f1801ed710"
    - ./check-version.sh intro-HPC | grep "Checksum for intro-HPC is still valid"
    - ./check-version.sh intro-Linux | grep "Checksum for intro-Linux is still valid"
install:
    - ./travis-install.sh
    - export PATH=$CACHEDIR/.texlive/bin/x86_64-linux:$PATH
    - pdflatex --version ; latexmk --version
script:
    - cd $TRAVIS_BUILD_DIR
    - make all
after_success:
    - mkdir -p $HOME/build
    - cp -a */*.pdf $HOME/build
    - ls $HOME/build
deploy:
  skip_cleanup: true
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  on:
      repo: $GITHUB_REPO
      branch: master

cache:
    directories:
        - $CACHEDIR
